version: '3.8'

services:
  backend:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    restart: always
