version: '3.8'

services:
  backend:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3000"  # Внешний 3500 → Внутренний 3000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: always
