name: Deploy React App to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: 217.25.88.96
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build/"
          target: "/home/deploy/orioncrew/frontend"

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 217.25.88.96
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
